title: Hello World!
author: Mica Paderni
email: mica_paderni@hotmail.com
description: > # this will appear in your document Head meta data for Google search results.
  Data Science and Social Explorer of this wild World called Earth ! 

# social links
twitter_username: micapaderni # DO NOT include the @ character, or else the build will fail!
github_username:  mikol-e # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
